1. Create an array of size [10,50] and use the random function to fill it with integers between 1 and 500 (inclusive). Load it to a DataFrame.

2. Calculate the sum of each row; the sum of each column; and the sum of all entries.

3. Determine the minimum; maximum; average; and standard deviation of all entries.

4. Sort the DataFrame: a) sort on column 2; b) sort on row 2.

In [1]:
# Load the library
import numpy as np
import pandas as pd

In [2]:
# creating the matrix with a small dataset.
matrix_1 = np.random.randint(1,15,15).reshape(3,5); matrix_1

array([[11, 13, 11,  7,  5],
       [ 4,  7,  2, 12,  5],
       [11, 10, 12,  2,  7]])

In [3]:
sum_rows = np.sum(matrix_1, axis=0); print('Sum of all rows of the matrix: ', sum_rows)
sum_cols = np.sum(matrix_1, axis=1); print('Sum of all columns of the matrix: ',sum_cols)
sum_all = np.sum(matrix_1);          print('Sum of all elements of the matrix: ',sum_all)

Sum of all rows of the matrix:  [26 30 25 21 17]
Sum of all columns of the matrix:  [47 30 42]
Sum of all elements of the matrix:  119


In [4]:
# sample size of 20 
# this is doing the full task on a smaller dataset before using a bigger data set
df_test = pd.DataFrame(matrix_1);df_test

0   1   2   3  4
0  11  13  11   7  5
1   4   7   2  12  5
2  11  10  12   2  7

In [5]:
# sort the dataframe by row 2
df_test.sort_values(by = 2, axis = 1, ascending=True)

3  4   1   0   2
0   7  5  13  11  11
1  12  5   7   4   2
2   2  7  10  11  12

In [6]:
# sort the dataframe by column 2
df_test.sort_values(by = 2, axis = 0, ascending=True)

0   1   2   3  4
1   4   7   2  12  5
0  11  13  11   7  5
2  11  10  12   2  7

In [7]:
# This is using the full dataset (1 to 500)
# Setting the seed for regeneration
np.random.seed(1)
# Generate 500 random integers between 1 and 500 (inclusive)
elem = np.random.randint(1,500,500)
elem

array([ 38, 236, 397,  73, 256, 394, 204, 134, 336, 449, 145, 130, 461,
        72, 238, 391, 282, 179, 277, 255, 358, 403, 469, 396, 253, 491,
       157, 414, 399,  51,  69, 216, 472, 490, 242, 479, 353,  87, 142,
       490, 394,   8, 320, 318,  23, 314,   2, 385, 317, 210, 265, 217,
       142, 116, 432, 491, 122, 457,  31,  72, 388, 455, 406,  50, 314,
         4, 453, 281, 498,  44,  77,  27, 309, 337, 110, 372, 298, 467,
        16,  65, 197,  26, 368, 227, 472, 392, 283, 154, 105,  23, 266,
       196, 488, 127, 280, 382, 357, 156, 422, 314,  84, 167, 137, 289,
       419, 267, 280, 144, 240,  88, 282, 456, 244, 349,  75, 191, 303,
       417, 217, 152, 184, 322, 370, 334, 260, 385, 254, 462, 263,  53,
       470, 455,   3,  77, 476, 150, 204, 264,  78, 201,  76, 333,  44,
        21,  31,  37, 360, 264, 302, 453,  58, 241, 211,  97, 270,  11,
       280, 381, 338, 392, 378, 153, 203, 477, 149, 417, 141, 194,  95,
        61, 490, 153, 339, 372, 354, 131, 493, 221, 104, 355, 26

In [8]:
# Create a matrix of shape [3,2]
matrix = elem.reshape(10,50); matrix

array([[ 38, 236, 397,  73, 256, 394, 204, 134, 336, 449, 145, 130, 461,
         72, 238, 391, 282, 179, 277, 255, 358, 403, 469, 396, 253, 491,
        157, 414, 399,  51,  69, 216, 472, 490, 242, 479, 353,  87, 142,
        490, 394,   8, 320, 318,  23, 314,   2, 385, 317, 210],
       [265, 217, 142, 116, 432, 491, 122, 457,  31,  72, 388, 455, 406,
         50, 314,   4, 453, 281, 498,  44,  77,  27, 309, 337, 110, 372,
        298, 467,  16,  65, 197,  26, 368, 227, 472, 392, 283, 154, 105,
         23, 266, 196, 488, 127, 280, 382, 357, 156, 422, 314],
       [ 84, 167, 137, 289, 419, 267, 280, 144, 240,  88, 282, 456, 244,
        349,  75, 191, 303, 417, 217, 152, 184, 322, 370, 334, 260, 385,
        254, 462, 263,  53, 470, 455,   3,  77, 476, 150, 204, 264,  78,
        201,  76, 333,  44,  21,  31,  37, 360, 264, 302, 453],
       [ 58, 241, 211,  97, 270,  11, 280, 381, 338, 392, 378, 153, 203,
        477, 149, 417, 141, 194,  95,  61, 490, 153, 339, 372, 354, 131,
     

In [9]:
# Loading the matrix into a dataframe
df = pd.DataFrame(matrix); df

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   38  236  397   73  256  394  204  134  336  449  ...  394    8  320  318   
1  265  217  142  116  432  491  122  457   31   72  ...  266  196  488  127   
2   84  167  137  289  419  267  280  144  240   88  ...   76  333   44   21   
3   58  241  211   97  270   11  280  381  338  392  ...  177   55   16  390   
4  486  398  498  115   98  182  341   11   97  184  ...   78  220  178  370   
5  145  413  235   46  452  373  323  463  303  385  ...  170  321  109  212   
6  159  476  399  276  252  155  236   87  392  228  ...  146  325  321  189   
7  151  295  170  459  206  327  154  231  241   49  ...   72   15  206  144   
8  239  414   45   38  151  476  439  333   13  377  ...  481  411  341   31   
9   71  141  296  231   84  240  177  318  455  270  ...  442  292  426  338   

    44   45   46   47   48   49  
0   23  314    2  385  317  210  
1  280  382  357  156  422  314  
2   31   37  360  264  302  453  
3  402  171   21  119  433  279  
4  304  462  425  463   46  344  
5   25  114  491  277   45  272  
6  207  146  168  164  466  157  
7  410  310  213  443  470  115  
8  360   65  151   99  309  132  
9  259  214   94  165  110  303  

[10 rows x 50 columns]

In [10]:
# Calculate the sum of each row; the sum of each column; and the sum of all entries.

sum_rows = np.sum(matrix, axis=0); print('Sum of all rows of the matrix: ', sum_rows)
sum_cols = np.sum(matrix, axis=1); print('Sum of all columns of the matrix: ',sum_cols)
sum_all = np.sum(matrix);          print('Sum of all elements of the matrix: ',sum_all)

Sum of all rows of the matrix:  [1696 2998 2530 1740 2620 2916 2556 2559 2446 2494 2639 2885 3400 2848
 2212 3027 2501 2265 3432 2090 2554 2193 2712 3190 2195 2406 2739 3353
 2488 1568 2375 2483 2390 2370 2769 2659 2047 2514 1243 2510 2302 2176
 2449 2140 2301 2215 2282 2535 2920 2579]
Sum of all columns of the matrix:  [13669 12551 11987 12935 12958 10919 12359 12180 12247 12706]
Sum of all elements of the matrix:  124511


In [11]:
# Determine the minimum; maximum; average; and standard deviation of all entries.

min_all = np.min(matrix);print('Minimum of all entries: ',min_all)
max_all = np.max(matrix); print('Maximum of all entries: ',max_all)
avg_all = np.mean(matrix); print('Average of all entries: ',avg_all)
sd_all = np.std(matrix); print('Standard dev of all entries: ',sd_all)

Minimum of all entries:  2
Maximum of all entries:  498
Average of all entries:  249.022
Standard dev of all entries:  141.81078067622363


In [12]:
# Showing the unsorted dataframe once again before sorting by rows and columns
df

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   38  236  397   73  256  394  204  134  336  449  ...  394    8  320  318   
1  265  217  142  116  432  491  122  457   31   72  ...  266  196  488  127   
2   84  167  137  289  419  267  280  144  240   88  ...   76  333   44   21   
3   58  241  211   97  270   11  280  381  338  392  ...  177   55   16  390   
4  486  398  498  115   98  182  341   11   97  184  ...   78  220  178  370   
5  145  413  235   46  452  373  323  463  303  385  ...  170  321  109  212   
6  159  476  399  276  252  155  236   87  392  228  ...  146  325  321  189   
7  151  295  170  459  206  327  154  231  241   49  ...   72   15  206  144   
8  239  414   45   38  151  476  439  333   13  377  ...  481  411  341   31   
9   71  141  296  231   84  240  177  318  455  270  ...  442  292  426  338   

    44   45   46   47   48   49  
0   23  314    2  385  317  210  
1  280  382  357  156  422  314  
2   31   37  360  264  302  453  
3  402  171   21  119  433  279  
4  304  462  425  463   46  344  
5   25  114  491  277   45  272  
6  207  146  168  164  466  157  
7  410  310  213  443  470  115  
8  360   65  151   99  309  132  
9  259  214   94  165  110  303  

[10 rows x 50 columns]

In [13]:
# Sort dataframe by column 2
df.sort_values(by =2, axis = 0, ascending=True)

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
8  239  414   45   38  151  476  439  333   13  377  ...  481  411  341   31   
2   84  167  137  289  419  267  280  144  240   88  ...   76  333   44   21   
1  265  217  142  116  432  491  122  457   31   72  ...  266  196  488  127   
7  151  295  170  459  206  327  154  231  241   49  ...   72   15  206  144   
3   58  241  211   97  270   11  280  381  338  392  ...  177   55   16  390   
5  145  413  235   46  452  373  323  463  303  385  ...  170  321  109  212   
9   71  141  296  231   84  240  177  318  455  270  ...  442  292  426  338   
0   38  236  397   73  256  394  204  134  336  449  ...  394    8  320  318   
6  159  476  399  276  252  155  236   87  392  228  ...  146  325  321  189   
4  486  398  498  115   98  182  341   11   97  184  ...   78  220  178  370   

    44   45   46   47   48   49  
8  360   65  151   99  309  132  
2   31   37  360  264  302  453  
1  280  382  357  156  422  314  
7  410  310  213  443  470  115  
3  402  171   21  119  433  279  
5   25  114  491  277   45  272  
9  259  214   94  165  110  303  
0   23  314    2  385  317  210  
6  207  146  168  164  466  157  
4  304  462  425  463   46  344  

[10 rows x 50 columns]

In [14]:
# sort dataframe by row 2
df.sort_values(by = 2, axis = 1, ascending=True)

32   43   44   45   42   29   14   40   33   38  ...   22   25   17   4   \
0  472  318   23  314  320   51  238  394  490  142  ...  469  491  179  256   
1  368  127  280  382  488   65  314  266  227  105  ...  309  372  281  432   
2    3   21   31   37   44   53   75   76   77   78  ...  370  385  417  419   
3  353  390  402  171   16  355  149  177  490  328  ...  339  131  194  270   
4  200  370  304  462  178   25  232   78  310   22  ...  117  206   26   98   
5  110  212   25  114  109  223  438  170  100   51  ...  289   56  131  452   
6   88  189  207  146  321   80  244  146  417  227  ...  212  167  229  252   
7  381  144  410  310  206  192  183   72  132   55  ...   52  124  273  206   
8  309   31  360   65  341  185  216  481   90  128  ...  113  227   44  151   
9  106  338  259  214  426  339  123  442   37  107  ...  442  247  491   84   

    49   31   11   27   30   34  
0  210  216  130  414   69  242  
1  314   26  455  467  197  472  
2  453  455  456  462  470  476  
3  279  183  153  221  267  339  
4  344  451   57  444  138  326  
5  272  137   64  288  331   33  
6  157  370  432  232   64  299  
7  115  175  447  408   22  441  
8  132   74  411  172  454   28  
9  303  396  280  245  363  113  

[10 rows x 50 columns]

In [1]:
from nltk.tokenize import word_tokenize
string = ['well its great that he did something about those beliefs while he was in office i doubt trump would fight the un for it so im really really happy obama did something while he couldoh wait',
 'you are right mr president']
word_tokenize(string)

ModuleNotFoundError: No module named 'regex'