In [6]:
# Load library
import numpy as np
from scipy import sparse 

In [2]:
# Create a vector as a row
vector_row = np.array([1,2,3])

In [3]:
#Create a vector as a column
vector_column = np.array([[1],
                        [2],
                        [3]])

In [5]:
# Creating a matrix
matrix = np.array([[1,2],[1,2],[1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [8]:
# Create a matrix
matrix = np.array([[0,0],[0,1],[3,0]])

# create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [9]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [13]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
# create a function that adds 100 to something
add_100 = lambda i: i + 100

# create a vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [14]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#broacasting
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [17]:
matrix = np.array([[1,1,1],[1,1,10],[1,1,15]])
matrix

array([[ 1,  1,  1],
       [ 1,  1, 10],
       [ 1,  1, 15]])

In [18]:
# rank of a matrix is the dimensions of the vector space spanned by its columns or rows

np.linalg.matrix_rank(matrix)

2

In [19]:
# the trace of a matrix is the sum of the diagonal elements
matrix.trace()

17

In [20]:
sum(matrix.diagonal())

17

In [21]:
#calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [22]:
eigenvalues

array([1.57972598e+01, 1.20274024e+00, 2.13480016e-16])

In [23]:
eigenvectors

array([[ 9.35154454e-02,  9.54818342e-01,  7.07106781e-01],
       [ 5.61805577e-01,  2.83317939e-01, -7.07106781e-01],
       [ 8.21966761e-01, -8.97378394e-02,  9.99962757e-17]])